### ISSUE TITLE
Show error message if not logged in

### ISSUE THREAD

**Issue by cbenhagen** [cadenasgmbh/3dfindit-freecad-integration#13]
Currently the send to freecad and download buttons simply do not work without showing any help to the user.

**Comment by tsielaff** [comment]
If not logged in, clicking on Send to FreeCAD should just open the login dialog. Is that not happening for you?

![image](https://user-images.githubusercontent.com/72011585/179481580-1c71c0da-067f-4c27-bb84-a18ba12d9feb.png)

**Comment by cbenhagen** [comment]
No the login window did not show.

**Comment by tsielaff** [comment]
Fixed.
