### ISSUE TITLE
An error occurred...

### ISSUE THREAD

**Issue by casterle** [cadenasgmbh/3dfindit-freecad-integration#15]
Upon opening the panel in FreeCAD 21.1 (or 21.2), the message "An error occurred..." is displayed n the panel.

FreeCAD logs the following errors:
(js) Uncaught error: TypeError: window.crypto.randomUUID is not a function [object Object]
(js) TypeError: window.crypto.randomUUID is not a function

OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * 3DfindIT 1.2.0
  * A2plus 0.4.61
  * Assembly4 0.50.6
  * Curves 0.6.22
  * fasteners 0.5.0
  * freecad.gears 1.2.0
  * lattice2 1.0.0
  * Manipulator 1.5.6
  * OpenDark 2023.12.17
  * parts_library
  * PieMenu 1.2.7
  * Pyramids-and-Polyhedrons
  * SearchBar 1.0.2 (Disabled)
  * SelectorToolbar
  * Silk 0.1.5

**Comment by tsielaff** [comment]
I can reproduce this issue. We'll fix it. Thanks for the report.

**Comment by tsielaff** [comment]
Fixed. No update of the plugin is required as this was fixed on 3dfindit.com.

**Comment by casterle** [comment]
Thanks for the quick response!

 

Happy New Year,

 

Leroy
