### ISSUE TITLE
Problem showing 3dfindit

### ISSUE THREAD

**Issue by kkoksvik** [cadenasgmbh/3dfindit-freecad-integration#8]
When launching 3dfindit plugin i get:

22:50:10  cannot import name 'QtWebEngineWidgets' from 'PySide2' (/usr/lib/python3/dist-packages/PySide2/__init__.py)

FreeCad-daily on Kubuntu 20.10

OS: Ubuntu 20.10 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.
Build type: Release
Branch: unknown
Hash: d03262cc41e141b4e713cb620f0f35395eb0d6a9
Python version: 3.8.6
Qt version: 5.14.2
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by berndhahnebach** [comment]
install these packages:

```
python3-pyqt5.qtwebchannel
python3-pyside2.qtwebenginewidgets 
```

**Comment by kkoksvik** [comment]
Fantastic, works like a charm :-)

**Comment by berndhahnebach** [comment]
means it could be closed?
