### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by snelweg** [cadenasgmbh/3dfindit-freecad-integration#9]
Nothing works, the toolbar is there but nothing happens when I click.

I tried:

> from freecad.cadenas3dfindit import dialog
dialog.toggle()

Result:

`>>> from freecad.cadenas3dfindit import dialog
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/ton/.FreeCAD/Mod/3DfindIT/freecad/cadenas3dfindit/dialog.py", line 22, in <module>
    from PySide2 import QtWebEngineWidgets    
ImportError: cannot imp`

Using:

> OS: Debian GNU/Linux 10 (buster) (X-Cinnamon/lightdm-xsession)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.28319 (Git)
Build type: Unknown
Branch: LinkDaily
Hash: d5ffb270e1e8b63e007c74f655b781532fcf501b
Python version: 3.7.3
Qt version: 5.11.3
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

**Comment by tsielaff** [comment]
From past experience, this is usually the case if your FreeCAD package is missing some Qt components.

**Comment by snelweg** [comment]
The answer is not really helpful. What is missing and how do I get it?
